services:
  # Backend API
  - type: web
    name: digitalstore-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Host=aws-1-ap-south-1.pooler.supabase.com;Port=6543;Database=postgres;Username=postgres.gdoaxftrniznvhrtaxnr;Password=@Congthanhx1;SSL Mode=Require;Trust Server Certificate=true"
      - key: Jwt__SecretKey
        generateValue: true
      - key: Jwt__Issuer
        value: DigitalStore.API
      - key: Jwt__Audience
        value: DigitalStore.Client

  # Frontend Static Site
  - type: web
    name: digitalstore-web
    runtime: static
    staticPublishPath: src/DigitalStore.Client
