services:
  # Backend API
  - type: web
    name: digitalstore-api
    runtime: docker
    plan: free
    healthCheckPath: /api/products
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Host=db.gdoaxftrniznvhrtaxnr.supabase.co;Database=postgres;Username=postgres;Password=@Congthanhx1;Port=5432;SSL Mode=Require;Trust Server Certificate=true"
      - key: Jwt__SecretKey
        generateValue: true
      - key: Jwt__Issuer
        value: DigitalStore.API
      - key: Jwt__Audience
        value: DigitalStore.Client

  # Frontend Static Site
  - type: web
    name: digitalstore-web
    runtime: static
    staticPublishPath: src/DigitalStore.Client
